### ISSUE TITLE
filter messages on the MQTT push server

### ISSUE THREAD

**Issue by bam80** [RadioShuttle/MQTTPushClient_Android#1]
Hi, thanks for the making such app open source, it's the only one I found!
> The app communicates via the MQTT push server only. The MQTT push server monitors the MQTT messages for the specified accounts and sends push messages via Google (Android) and Apple (iOS) to corresponding mobile devices connected to this account. In addition, the server keeps the last 100 MQTT push messages for each account.

> The mobile device receives and displays push messages even if the app is not running. Once the app is started, it will display received messages in its messages view. At the same time it will update the latest messages from the MQTT push server to ensure that it is up to date.

> The dashboard view will not connect to the MQTT server for the dash gallery view, instead it will communicate with the MQTT push server only. The MQTT push server remembers the latest message for each registered topic, therefore the display should represent the latest data (e.g. lights on or off, temperature, etc.).

If the app is not running, I wouldn't like to receive all the push messages on device for every MQTT message, even if they are without notification.
I would better prefer to receive ALARMs via push only, and then load other data upon the app opening.
Is it possible?
I saw there is message filter with JS field accessible for every widget, where does that filtering happen - on server or in the app itself?
If it's on the server, isn't it a solution for my request?

**Comment by helmut64** [comment]
As already answered by e-mail. It is possible to disable push messages in the topics settings. Go to server-list -> Edit -> MQTT Topics, select the topic, set notifications to None or disabled.

**Comment by helmut64** [comment]
closed

**Comment by bam80** [comment]
> As already answered by e-mail.

Did you send me an email? I didn't receive anything.
