### ISSUE TITLE
JSON's more than 256 bytes are сut off and can't be parsed

### ISSUE THREAD

**Issue by bam80** [RadioShuttle/MQTTPushClient_Android#2]
It was established 256 bytes is too small for the restriction, so it's definitely a problem with this app:
https://github.com/theengs/gateway/issues/193

**Comment by helmut64** [comment]
This is all correct and done by purpose. We need to ensure that push messages are as short as possible to avoid overloading push messages against the vendors Apple/Google. Another reason is also that we cache recent messages on the server to show them on mobile. One more reason is that we forward messages to our LoRa boards, again a payload limit of 256 bytes. This limit reasonable and will not be increased.

**Comment by bam80** [comment]
Am I understand right it only applies to a push notification topics subscribed and not to a widget's topics?
For the latter, I suppose the restriction is 256 kB instead?

> Keep the size of your message content small! Messages larger than 256 kB will be ignored and not delivered as a push message. If the content of a push notification is larger than 255 bytes, it will always be truncated.

https://help.radioshuttle.de/mqttapp/1.0/en/dashboard.html

**Comment by helmut64** [comment]
The server stored message can be up to 256kB, however only a single last message is stored on the server to recover the dash board. For regular push messages there are the 100 last messages stored which allows to see missed/historical messages.
My option is to reduce the message size to something up to 255 characters which means everything works. Use a separate TCP/IP stream to your server for other stuff e.g. videos pictures etc. which can be done in JavaScript in the gallery mode.

**Comment by bam80** [comment]
Sorry it's still not clear to me what messages the 256 bytes restriction applies.
As pointed in the original issue, jsons > 256 bytes are quite common even without videos/pictures etc.: https://github.com/theengs/gateway/issues/193#issuecomment-1867958013

I would need to do my tests again to see if we still have a problem here.
